language: c
sudo: required
services:
  - docker

before_script:
  - docker pull rauc/testing:latest
  - docker run --name rauc-ci -itd -v "$PWD":/home/travis -w /home/travis --tmpfs /tmp/uml:exec,mode=777 --tmpfs /tmp:exec -u travis rauc/testing:latest bash

coverity_scan:
  project:
    name: "jluebbe/rauc"
    description: "Robust Auto-Update Controller"
  notification_email: jlu@pengutronix.de
  build_command_prepend: "cov-configure --comptype gcc --compiler gcc-7 --template && ./autogen.sh && ./configure"
  build_command: "make -j2"
  branch_pattern: master

script:
  - docker exec -it rauc-ci ./autogen.sh
  - docker exec -it rauc-ci ./configure --enable-code-coverage
  - docker exec -it rauc-ci make clean
  - docker exec -it rauc-ci make -j2
  - docker exec -it rauc-ci make doc SPHINXOPTS=-W
  - docker exec -it rauc-ci make check TESTS=
  - docker exec -it rauc-ci /bin/sh -c 'export TMPDIR=/tmp/uml && ./uml-test'
  - docker exec -it rauc-ci make distcheck
  - docker exec -it rauc-ci /bin/sh -c 'cd /home/travis/contrib/cgi && ./autogen.sh && ./configure && make clean && make -j2 && make distcheck'
  - docker exec -it rauc-ci ./uncrustify.sh && git diff --exit-code
after_success:
  - docker exec -it rauc-ci coveralls --build-root '.' --exclude test --exclude rauc-installer-generated.c
after_failure:
  - cat test/*.log
  - cat test-suite.log
  - cat rauc-*/_build/sub/test-suite.log
